services:
  velocity:
    image: mrletsplay/velocity
    stdin_open: true
    tty: true
    stop_grace_period: 10m
    ports:
      - "25565:25577"
    volumes:
      - "./velocity:/velocity"
    networks:
      - velocity
    environment:
      - "VELOCITY_SECRET=${VELOCITY_SECRET}"
      - "VELOCITY_UPDATE_ON_START=${VELOCITY_UPDATE_ON_START}"
  server1:
    image: mrletsplay/paper:1.19.4
    stdin_open: true
    tty: true
    stop_grace_period: 10m
    volumes:
      - "./server1:/minecraft"
    networks:
      - velocity
    environment:
      - "EULA=${EULA}"
      - "VELOCITY_ENABLE=${VELOCITY_ENABLE}"
      - "VELOCITY_SECRET=${VELOCITY_SECRET}"
      - "PAPER_UPDATE_ON_START=${PAPER_UPDATE_ON_START}"
  server2:
    image: mrletsplay/paper:1.18.2
    stdin_open: true
    tty: true
    stop_grace_period: 10m
    volumes:
      - "./server2:/minecraft"
    networks:
      - velocity
    environment:
      - "EULA=${EULA}"
      - "VELOCITY_ENABLE=${VELOCITY_ENABLE}"
      - "VELOCITY_SECRET=${VELOCITY_SECRET}"
      - "PAPER_UPDATE_ON_START=${PAPER_UPDATE_ON_START}"
networks:
  velocity:
